language: cpp

sudo: required
dist: trusty

compiler:
  - gcc

os:
  - linux

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -q gcc-4.8 g++-4.8 libstdc++-4.8-dev libboost-all-dev -y libcppunit-dev libboost-all-dev libhdf5-serial-dev libhdf5-dev libhdf5-7;
  - sudo apt-get install qt5-default qttools5-dev-tools -y;
  - g++ --version
  # build nix library
  - mkdir nix-build
  - cd nix-build
  - git clone https://github.com/G-Node/nix
  - cd nix
  - mkdir build
  - cd build
  - cmake -DBUILD_TESTING=OFF ..
  - make all
  - sudo make install
  - cd ../../..
  
install:
  - if [ "$CXX" == "g++" ]; then 
    export CXX="g++-4.8"; 
    export COMPILER="g++";
    $CXX --version; 
    else 
    clang --version;
    fi

script: cmake . && make
